### PR TITLE
don't remove empty manifests when all payload files are removed

### LINKED ISSUE #38: manifest file is removed when calling removePayloadFile and save
When calling `bag.removePayloadFile(...).save()` on a bag with only one payload file, the payload manifest(s) is/are removed, which causes `.save()` to fail with `IllegalStateException: bag must contain at least one payload manifest`.

Thanks to @jo-pol for reporting.

### PR DESCRIPTION
**Pull request by rvanheest**
fixes #38

solution:
* empty payload manifests due to all files being removed are no longer deleted themselves (`DansBagV0`)
* adjusted an incorrect test (`ManifestSpec`)
* added an extra test on `.save()` (`SaveSpec`)

### CODE REVIEW

File: src/main/scala/nl/knaw/dans/bag/v0/DansV0Bag.scala [hunk 1]
```diff
@@ -882,11 +882,7 @@ class DansV0Bag private(private[v0] val locBag: LocBag) extends DansBag {
          fileChecksumMap = manifest.getFileToChecksumMap)
       fileChecksumMap.remove(file.path)
 
-    setManifests {
-      manifests.asScala.toList
-        .filterNot(_.getFileToChecksumMap.isEmpty)
-        .toSet.asJava
-    }
+    setManifests(manifests.asScala.toList.toSet.asJava)
```
Comment (rvanheest) [inline src/main/scala/nl/knaw/dans/bag/v0/DansV0Bag.scala]: Maybe this line is not necessary... Need to check that after lunch...

Comment (rvanheest) [reply src/main/scala/nl/knaw/dans/bag/v0/DansV0Bag.scala]: nope, we don't! that changes things for the better!
